sudo: required
dist: bionic
language: python
python:
    - "2.7"
addons:
  apt:
    sources:
    - sourceline: 'deb http://mirror2.openio.io/pub/repo/openio/sds/19.10/ubuntu/ bionic/'
      key_url: 'http://mirror2.openio.io/pub/repo/openio/APT-GPG-KEY-OPENIO-0'
    packages:
    - python-zookeeper # Required because not published on pypi

env:
  matrix:
    - TEST_SUITE=s3 # Latest stable/supported versions
    - TEST_SUITE=s3 SDS_BRANCH=master SWIFT_BRANCH=master # Integration with latest versions
    - TEST_SUITE=encryption
    - TEST_SUITE=encryption SDS_BRANCH=master SWIFT_BRANCH=master
    - TEST_SUITE=swift
    - TEST_SUITE=swift SDS_BRANCH=master SWIFT_BRANCH=master
    - TEST_SUITE=ns-wide-versioning
    - TEST_SUITE=ns-wide-versioning SDS_BRANCH=master SWIFT_BRANCH=master
    - TEST_SUITE=unit
    - TEST_SUITE=unit SDS_BRANCH=master SWIFT_BRANCH=master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes python-virtualenv jq liberasurecode-dev libssl-dev libattr1-dev libleveldb-dev libzookeeper-mt-dev

install:
  - echo -en "travis_fold:start:install\r"
  - pip install --upgrade pip setuptools virtualenv tox flake8
  - test -n "$SWIFT_BRANCH" && git config --local submodule.third_party/swift.branch "$SWIFT_BRANCH" || true
  - test -n "$SDS_BRANCH" && git config --local submodule.third_party/oio-sds.branch "$SDS_BRANCH" || true
  - git submodule update --init --remote
  - ( grep -v -e "PyECLib" -e "requests" -e "six" third_party/oio-sds/all-requirements.txt ; grep -v -e "eventlet" -e "lxml" third_party/swift/requirements.txt ) | sort > deps-requirements.txt
  - pip install --upgrade -r deps-requirements.txt
  - cd third_party/oio-sds && python setup.py install && cd ../..
  - cd third_party/swift && python setup.py install && cd ../..
  - cd third_party/swift3 && python setup.py install && cd ../..
  - python setup.py develop
  - pip install --upgrade -r test-requirements.txt
  - go get gopkg.in/ini.v1 golang.org/x/sys/unix
  - echo -en "travis_fold:end:install\r"

script:
  - set -e
  - flake8 oioswift tests
  - ./tests/run_tests.sh "$TEST_SUITE"

after_success:
  - codecov -X gcov
