sudo: required
dist: trusty
language: python
addons:
  apt:
    sources:
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse'
    - sourceline: 'deb http://mirror.openio.io/pub/repo/openio/sds/17.04/ubuntu/trusty ./'
    update: true

env:
  matrix:
    - TEST_SUITE=encryption
    - TEST_SUITE=ns-wide-versioning
    - TEST_SUITE=s3
    - TEST_SUITE=unit
    - TEST_SUITE=encryption SWIFT_BRANCH=stable/pike
    - TEST_SUITE=ns-wide-versioning SWIFT_BRANCH=stable/pike
    - TEST_SUITE=s3 SWIFT_BRANCH=stable/pike
    - TEST_SUITE=unit SWIFT_BRANCH=stable/pike

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes python-virtualenv jq liberasurecode-dev libssl-dev libattr1-dev libleveldb1 libleveldb-dev libzookeeper-mt-dev

install:
  - virtualenv $HOME/venv
  - source $HOME/venv/bin/activate
  - pip install --upgrade pip setuptools virtualenv tox flake8
  - test -n "$SWIFT_BRANCH" && git config --local submodule.third_party/swift.branch "$SWIFT_BRANCH" || true
  - git submodule update --init --remote
  - ( grep -v PyECLib third_party/oio-sds/all-requirements.txt ; grep -v eventlet third_party/swift/requirements.txt ) > deps-requirements.txt
  - pip install --upgrade -r deps-requirements.txt
  - cd third_party/oio-sds && python setup.py install && cd ../..
  - cd third_party/swift && python setup.py install && cd ../..
  - cd third_party/swift3 && python setup.py install && cd ../..
  - python setup.py develop
  - pip install --upgrade -r test-requirements.txt

script:
  - flake8 oioswift tests
  - ./tests/run_tests.sh "$TEST_SUITE"

after_success:
  - bash <(curl -s https://codecov.io/bash) -f cmake_coverage.output
  - codecov
