sudo: required
dist: trusty
language: python

env:
  matrix:
    - TEST_SUITE=unit
    - TEST_SUITE=ns-wide-versioning
    - TEST_SUITE=s3

install:
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
  - sudo apt-add-repository "deb http://mirror.openio.io/pub/repo/openio/sds/17.04/ubuntu/trusty ./"
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes python-virtualenv liberasurecode-dev libssl-dev libattr1-dev libleveldb1 libleveldb-dev libzookeeper-mt-dev
  - virtualenv $HOME/venv
  - source $HOME/venv/bin/activate
  - pip install --upgrade pip setuptools virtualenv tox flake8
  - git submodule update --init --remote
  - ( grep -v PyECLib third_party/oio-sds/all-requirements.txt ; grep -v eventlet third_party/swift/requirements.txt ) > deps-requirements.txt
  - pip install --upgrade -r deps-requirements.txt
  - cd third_party/oio-sds && python setup.py install && cd ../..
  - cd third_party/swift && python setup.py install && cd ../..
  - cd third_party/swift3 && python setup.py install && cd ../..
  - python setup.py install
  - pip install --upgrade -r test-requirements.txt

script:
  - flake8 oioswift
  - ./tests/run_tests.sh "$TEST_SUITE"

after_success:
  - bash <(curl -s https://codecov.io/bash) -f cmake_coverage.output
  - codecov
