sudo: required
dist: trusty
language: python

install:
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes python-virtualenv liberasurecode-dev libssl-dev libattr1-dev libleveldb1 libleveldb-dev
  - virtualenv $HOME/venv
  - source $HOME/venv/bin/activate
  - pip install --upgrade pip setuptools virtualenv tox
  - git submodule update --init --remote
  - cd third_party/oio-sds && pip install --upgrade -r all-requirements.txt && python setup.py install && cd ../..
  - cd third_party/swift && pip install --upgrade -r requirements.txt && python setup.py install && cd ../..
  - pip install --upgrade -r test-requirements.txt

script:
  - nosetests -v tests/unit/controllers
  - nosetests -v tests/unit/common/middleware/test_versioned_writes.py:OioVersionedWritesTestCase
